version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: npm run test -- --collectCoverage=true
      - store_artifacts:
          path: coverage
