export const FETCH_POPULAR_MOVIES_START = "FETCH_POPULAR_MOVIES_START";
export const FETCH_POPULAR_MOVIES_SUCCESS = "FETCH_POPULAR_MOVIES_SUCCESS";
export const FETCH_POPULAR_MOVIES_FAIL = "FETCH_POPULAR_MOVIES_FAIL";
