export const FETCH_MOVIES_BY_GENRE_START = "FETCH_MOVIES_BY_GENRE_START";
export const FETCH_MOVIES_BY_GENRE_SUCCESS = "FETCH_MOVIES_BY_GENRE_SUCCESS";
export const FETCH_MOVIES_BY_GENRE_FAIL = "FETCH_MOVIES_BY_GENRE_FAIL";
